backend:
  replicaCount: 1
  image:
    repository: 510491242343.dkr.ecr.us-east-1.amazonaws.com/bombo-086
    tag: back-latest
  port: 5000
  env:
    DB_HOST: postgres-postgresql.pg.svc.cluster.local
    DB_NAME: appdb
    DB_USER: appuser
    DB_PASSWORD: apppassword
  storageClass: aws-pg-sc
  storageSize: 8Gi

frontend:
  replicaCount: 1
  image:
    repository: 510491242343.dkr.ecr.us-east-1.amazonaws.com/bombo-086
    tag: front-latest
  port: 80
  ingress:
    host: ""
    class: nginx
