name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push Frontend & Backend to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build & Push Frontend
    - name: Build and Push Frontend Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: bombo-086
        IMAGE_TAG: front-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f front/Dockerfile front
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Build & Push Backend
    - name: Build and Push Backend Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: bombo-086
        IMAGE_TAG: back-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f back/Dockerfile back
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
